In [ ]:
import requests
import pandas as pd
import pickle
from time import sleep
from random import shuffle

In [ ]:
# df = pd.read_pickle("./listaPlayersNomeJogo.pkl")
df = pd.read_pickle("./jogosInfo.pkl")
df

,num,nome,currentPlayers,peak24h,allTimePeak,gameID,dados,tags
0,1,Counter-Strike 2,1274295,1527573,1818773,730,"{'type': 'game', 'name': 'Counter-Strike 2', '...","[FPS, Shooter, Multiplayer, Competitive, Actio..."
1,2,Dota 2,697691,716906,1295114,570,"{'type': 'game', 'name': 'Dota 2', 'steam_appi...","[Free to Play, MOBA, Multiplayer, Strategy, eS..."
2,3,PUBG: BATTLEGROUNDS,450881,631467,3257248,578080,"{'type': 'game', 'name': 'PUBG: BATTLEGROUNDS'...","[Survival, Shooter, Battle Royale, Multiplayer..."
3,4,Apex Legends,245878,357225,624473,1172470,"{'type': 'game', 'name': 'Apex Legends™', 'ste...","[Free to Play, Battle Royale, Multiplayer, FPS..."
4,5,Source SDK Base 2007,168144,187294,221857,218,None,None
...,...,...,...,...,...,...,...,...
4995,4996,Devil Slayer - Raksasi / 斩妖Raksasi,20,26,1080,1016600,"{'type': 'game', 'name': 'Devil Slayer - Raksa...","[Difficult, Action Roguelike, Top-Down, Action..."
4996,4997,DEEEER Simulator: Your Average Everyday Deer Game,20,25,251,1018800,"{'type': 'game', 'name': 'DEEEER Simulator: Yo...","[Exploration, Sandbox, Physics, Funny, Third P..."
4997,4998,Wanba Warriors,20,31,720,1021770,"{'type': 'game', 'name': ' Wanba Warriors', 's...","[Fighting, Multiplayer, Funny, Parody , PvP, L..."
4998,4999,Coloring Game,20,31,593,1026820,"{'type': 'game', 'name': 'Coloring Game', 'ste...","[Free to Play, Relaxing, Pixel Graphics, Casua..."
4999,5000,Blood Trail,20,40,154,1032430,"{'type': 'game', 'name': 'Blood Trail', 'steam...","[Gore, Violent, Action, VR, Horror, Early Acce..."

In [ ]:
df.iloc[0]["dados"]

{'type': 'game',
 'name': 'Counter-Strike 2',
 'steam_appid': 730,
 'required_age': 0,
 'is_free': True,
 'dlc': [2678630],
 'detailed_description': 'For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2.<br><br>A free upgrade to CS:GO, Counter-Strike 2 marks the largest technical leap in Counter-Strike’s history. Built on the Source 2 engine, Counter-Strike 2 is modernized with realistic physically-based rendering, state of the art networking, and upgraded Community Workshop tools.<br><br>In addition to the classic objective-focused gameplay that Counter-Strike pioneered in 1999, Counter-Strike 2 features:<br><br><ul class="bb_ul"><li>All-new CS Ratings with the updated Premier mode<br></li><li>Global and Regional leaderboards<br></li><li>Upgraded and overhauled maps<br></li><li>Game-changing dynamic smoke grenades<br></li><li>Tick-rate-independent gameplay<br></li><li>Redesigned visual effects and audio<br></li><li>All items from CS:GO moving forward to CS2</li></ul>',
 'about_the_game': 'For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2.<br><br>A free upgrade to CS:GO, Counter-Strike 2 marks the largest technical leap in Counter-Strike’s history. Built on the Source 2 engine, Counter-Strike 2 is modernized with realistic physically-based rendering, state of the art networking, and upgraded Community Workshop tools.<br><br>In addition to the classic objective-focused gameplay that Counter-Strike pioneered in 1999, Counter-Strike 2 features:<br><br><ul class="bb_ul"><li>All-new CS Ratings with the updated Premier mode<br></li><li>Global and Regional leaderboards<br></li><li>Upgraded and overhauled maps<br></li><li>Game-changing dynamic smoke grenades<br></li><li>Tick-rate-independent gameplay<br></li><li>Redesigned visual effects and audio<br></li><li>All items from CS:GO moving forward to CS2</li></ul>',
 'short_description': 'For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2.',
 'supported_languages': 'Czech, Danish, Dutch, English<strong>*</strong>, Finnish, French, German, Hungarian, Italian, Japanese, Korean, Norwegian, Polish, Portuguese - Portugal, Portuguese - Brazil, Romanian, Russian, Simplified Chinese, Spanish - Spain, Swedish, Thai, Traditional Chinese, Turkish, Bulgarian, Ukrainian, Greek, Spanish - Latin America, Vietnamese, Indonesian<br><strong>*</strong>languages with full audio support',
 'header_image': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/header.jpg?t=1716504320',
 'capsule_image': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/capsule_231x87.jpg?t=1716504320',
 'capsule_imagev5': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/capsule_184x69.jpg?t=1716504320',
 'website': 'http://counter-strike.net/',
 'pc_requirements': {'minimum': '<strong>Minimum:</strong><br><ul class="bb_ul"><li><strong>OS:</strong> Windows® 10<br></li><li><strong>Processor:</strong> 4 hardware CPU threads - Intel® Core™ i5 750 or higher<br></li><li><strong>Memory:</strong> 8 GB RAM<br></li><li><strong>Graphics:</strong> Video card must be 1 GB or more and should be a DirectX 11-compatible with support for Shader Model 5.0<br></li><li><strong>DirectX:</strong> Version 11<br></li><li><strong>Storage:</strong> 85 GB available space</li></ul>'},
 'mac_requirements': {'minimum': '<strong>Minimum:</strong><br><ul class="bb_ul"><li><strong>OS:</strong> MacOS X 10.11 (El Capitan) or later<br></li><li><strong>Processor:</strong> Intel Core Duo Processor (2GHz or better)<br></li><li><strong>Memory:</strong> 2 GB RAM<br></li><li><strong>Graphics:</strong> ATI Radeon HD 2400 or better / NVIDIA 8600M or better<br></li><li><strong>Storage:</strong> 15 GB available space</li></ul>'},
 'linux_requirements': {'minimum': '<strong>Minimum:</strong><br><ul class="bb_ul"><li><strong>OS:</strong> Ubuntu 20.04<br></li><li><strong>Processor:</strong> 4 hardware CPU threads - Intel® Core™ i5 750 or higher<br></li><li><strong>Memory:</strong> 8 GB RAM<br></li><li><strong>Graphics:</strong> AMD GCN+ or NVIDIA Kepler+ with up-to-date Vulkan drivers.  Support for VK_EXT_graphics_pipeline_library highly recommended.<br></li><li><strong>Storage:</strong> 85 GB available space<br></li><li><strong>Sound Card:</strong> Highly recommended</li></ul>'},
 'developers': ['Valve'],
 'publishers': ['Valve'],
 'packages': [329385, 298963, 54029],
 'package_groups': [{'name': 'default',
   'title': 'Buy Counter-Strike 2',
   'description': '',
   'selection_text': 'Select a purchase option',
   'save_text': '',
   'display_type': 0,
   'is_recurring_subscription': 'false',
   'subs': [{'packageid': 298963,
     'percent_savings_text': ' ',
     'percent_savings': 0,
     'option_text': 'Counter-Strike 2 - Free',
     'option_description': '',
     'can_get_free_license': '0',
     'is_free_license': True,
     'price_in_cents_with_discount': 0},
    {'packageid': 54029,
     'percent_savings_text': ' ',
     'percent_savings': 0,
     'option_text': 'Prime Status Upgrade - $14.99',
     'option_description': '',
     'can_get_free_license': '0',
     'is_free_license': False,
     'price_in_cents_with_discount': 1499}]}],
 'platforms': {'windows': True, 'mac': False, 'linux': True},
 'categories': [{'id': 1, 'description': 'Multi-player'},
  {'id': 27, 'description': 'Cross-Platform Multiplayer'},
  {'id': 29, 'description': 'Steam Trading Cards'},
  {'id': 30, 'description': 'Steam Workshop'},
  {'id': 35, 'description': 'In-App Purchases'},
  {'id': 8, 'description': 'Valve Anti-Cheat enabled'},
  {'id': 15, 'description': 'Stats'},
  {'id': 41, 'description': 'Remote Play on Phone'},
  {'id': 42, 'description': 'Remote Play on Tablet'},
  {'id': 43, 'description': 'Remote Play on TV'}],
 'genres': [{'id': '1', 'description': 'Action'},
  {'id': '37', 'description': 'Free to Play'}],
 'screenshots': [{'id': 0,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_796601d9d67faf53486eeb26d0724347cea67ddc.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_796601d9d67faf53486eeb26d0724347cea67ddc.1920x1080.jpg?t=1716504320'},
  {'id': 1,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_d830cfd0550fbb64d80e803e93c929c3abb02056.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_d830cfd0550fbb64d80e803e93c929c3abb02056.1920x1080.jpg?t=1716504320'},
  {'id': 2,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_13bb35638c0267759276f511ee97064773b37a51.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_13bb35638c0267759276f511ee97064773b37a51.1920x1080.jpg?t=1716504320'},
  {'id': 3,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_0f8cf82d019c614760fd20801f2bb4001da7ea77.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_0f8cf82d019c614760fd20801f2bb4001da7ea77.1920x1080.jpg?t=1716504320'},
  {'id': 4,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_ef82850f036dac5772cb07dbc2d1116ea13eb163.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_ef82850f036dac5772cb07dbc2d1116ea13eb163.1920x1080.jpg?t=1716504320'},
  {'id': 5,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_76f6730dbb911650ba1f41c8e5b4bac638b5beea.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_76f6730dbb911650ba1f41c8e5b4bac638b5beea.1920x1080.jpg?t=1716504320'},
  {'id': 6,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_808cdd373d78c3cf3a78e7026ebb1a15895e0670.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_808cdd373d78c3cf3a78e7026ebb1a15895e0670.1920x1080.jpg?t=1716504320'},
  {'id': 7,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_ef98db5d5a4d877531a5567df082b0fb62d75c80.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_ef98db5d5a4d877531a5567df082b0fb62d75c80.1920x1080.jpg?t=1716504320'},
  {'id': 8,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_2254a50f27951fb9028bc00b93a7f2ed7aac1e13.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_2254a50f27951fb9028bc00b93a7f2ed7aac1e13.1920x1080.jpg?t=1716504320'},
  {'id': 9,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_54b9c26b028c84d5f8a5316f31ae6203953ed84d.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_54b9c26b028c84d5f8a5316f31ae6203953ed84d.1920x1080.jpg?t=1716504320'},
  {'id': 10,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_1b3b5fd437939a7ed00a2155269e78994cb998d3.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_1b3b5fd437939a7ed00a2155269e78994cb998d3.1920x1080.jpg?t=1716504320'},
  {'id': 11,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_352666c1949ce3966bd966d6ea5a1afd532257bc.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_352666c1949ce3966bd966d6ea5a1afd532257bc.1920x1080.jpg?t=1716504320'},
  {'id': 12,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_63d2733b9b4ace01a41d5ba8afd653245d05d54a.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_63d2733b9b4ace01a41d5ba8afd653245d05d54a.1920x1080.jpg?t=1716504320'},
  {'id': 13,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_fe70d46859593aef623a0614f4686e2814405035.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_fe70d46859593aef623a0614f4686e2814405035.1920x1080.jpg?t=1716504320'},
  {'id': 14,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_bb2af3e83ac0385ff2055f2ab9697cdd83e351b7.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_bb2af3e83ac0385ff2055f2ab9697cdd83e351b7.1920x1080.jpg?t=1716504320'},
  {'id': 15,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_fb8e5e2ae29ce64e2898315c66b5db08989e8f91.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_fb8e5e2ae29ce64e2898315c66b5db08989e8f91.1920x1080.jpg?t=1716504320'},
  {'id': 16,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_0db84c628a798e38ca57d69abda119bee1358008.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_0db84c628a798e38ca57d69abda119bee1358008.1920x1080.jpg?t=1716504320'},
  {'id': 17,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_18e9ea2715f0407ee05e206073927a648db60d73.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_18e9ea2715f0407ee05e206073927a648db60d73.1920x1080.jpg?t=1716504320'},
  {'id': 18,
   'path_thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_2514675f364079b754b820cbc8b2e7c331d56a26.600x338.jpg?t=1716504320',
   'path_full': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/ss_2514675f364079b754b820cbc8b2e7c331d56a26.1920x1080.jpg?t=1716504320'}],
 'movies': [{'id': 256972298,
   'name': 'Launch Trailer',
   'thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256972298/movie.293x165.jpg?t=1696005467',
   'webm': {'480': 'http://cdn.akamai.steamstatic.com/steam/apps/256972298/movie480_vp9.webm?t=1696005467',
    'max': 'http://cdn.akamai.steamstatic.com/steam/apps/256972298/movie_max_vp9.webm?t=1696005467'},
   'mp4': {'480': 'http://cdn.akamai.steamstatic.com/steam/apps/256972298/movie480.mp4?t=1696005467',
    'max': 'http://cdn.akamai.steamstatic.com/steam/apps/256972298/movie_max.mp4?t=1696005467'},
   'highlight': True},
  {'id': 256970298,
   'name': 'Moving Beyond Tick Rate',
   'thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256970298/movie.293x165.jpg?t=1696005475',
   'webm': {'480': 'http://cdn.akamai.steamstatic.com/steam/apps/256970298/movie480_vp9.webm?t=1696005475',
    'max': 'http://cdn.akamai.steamstatic.com/steam/apps/256970298/movie_max_vp9.webm?t=1696005475'},
   'mp4': {'480': 'http://cdn.akamai.steamstatic.com/steam/apps/256970298/movie480.mp4?t=1696005475',
    'max': 'http://cdn.akamai.steamstatic.com/steam/apps/256970298/movie_max.mp4?t=1696005475'},
   'highlight': True},
  {'id': 256969703,
   'name': 'Leveling Up',
   'thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256969703/movie.293x165.jpg?t=1696005483',
   'webm': {'480': 'http://cdn.akamai.steamstatic.com/steam/apps/256969703/movie480_vp9.webm?t=1696005483',
    'max': 'http://cdn.akamai.steamstatic.com/steam/apps/256969703/movie_max_vp9.webm?t=1696005483'},
   'mp4': {'480': 'http://cdn.akamai.steamstatic.com/steam/apps/256969703/movie480.mp4?t=1696005483',
    'max': 'http://cdn.akamai.steamstatic.com/steam/apps/256969703/movie_max.mp4?t=1696005483'},
   'highlight': True},
  {'id': 256969690,
   'name': 'Responsive Smokes',
   'thumbnail': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/256969690/movie.293x165.jpg?t=1696005491',
   'webm': {'480': 'http://cdn.akamai.steamstatic.com/steam/apps/256969690/movie480_vp9.webm?t=1696005491',
    'max': 'http://cdn.akamai.steamstatic.com/steam/apps/256969690/movie_max_vp9.webm?t=1696005491'},
   'mp4': {'480': 'http://cdn.akamai.steamstatic.com/steam/apps/256969690/movie480.mp4?t=1696005491',
    'max': 'http://cdn.akamai.steamstatic.com/steam/apps/256969690/movie_max.mp4?t=1696005491'},
   'highlight': True}],
 'recommendations': {'total': 4114236},
 'achievements': {'total': 1,
  'highlighted': [{'name': 'A New Beginning',
    'path': 'https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/730/f75dd04fa12445a8ec43be65fa16ff1b8d2bf82e.jpg'}]},
 'release_date': {'coming_soon': False, 'date': 'Aug 21, 2012'},
 'support_info': {'url': '', 'email': ''},
 'background': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/page_bg_generated_v6b.jpg?t=1716504320',
 'background_raw': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/page.bg.jpg?t=1716504320',
 'content_descriptors': {'ids': [2, 5],
  'notes': 'Includes intense violence and blood.'},
 'ratings': {'usk': {'rating': '16',
   'descriptors': 'Gewalt; In-Game Käufe (+zufällige Objekte); Chats'},
  'agcom': {'rating': '16', 'descriptors': 'Violenza'},
  'cadpa': {'rating': '12'},
  'dejus': {'rating': '16', 'descriptors': 'Violência'}}}

In [ ]:
# df["dados"] = None

In [ ]:
lastFail = None

In [ ]:
# Realiza uma solicitação GET à API da Steam para obter detalhes de um aplicativo específico e converte a resposta JSON em um dicionário
requests.get(f"https://store.steampowered.com/api/appdetails?appids={lastFail}&cc=US").json()

{'2088380': {'success': False}}

In [ ]:
if lastFail is not None:

    tempo = 1
    sucesso = False
    # Loop para tentar obter informações até ter sucesso
    while not sucesso:
        try:
            getInfo(lastFail)
            sucesso = True
        except:
            print(f"Sleeping {tempo}")
            sleep(tempo)
            tempo = 2*tempo

Sleeping 1
Sleeping 2
Sleeping 4
Sleeping 8
Sleeping 16
Sleeping 32
Sleeping 64
Sleeping 128

In [ ]:
# Conjunto para armazenar os índices das linhas onde a coluna 'dados' é None
indicesNones = set()
for i in range(len(df)):
    if df.iloc[i]["dados"] is None:
        indicesNones.add(i)

len(indicesNones)

172

In [ ]:
# Função para obter informações do aplicativo a partir da API da Steam
def getInfo(appId):
    global lastFail
    try:
        aux = requests.get(f"https://store.steampowered.com/api/appdetails?appids={appId}&cc=US").json()
        if aux is None:
            lastFail = appId
            raise Exception(f"Parou de retornar com id={appId}")
            return None
        if aux[f"{appId}"]["success"] == False:
            return None
        data = aux[f"{appId}"]["data"]
    except Exception as e:
        # print(appId)
        raise e
    return data


# Tenta novamente obter informações do último aplicativo falhado, se existir
if lastFail is not None :
    try:
        getInfo(lastFail)
    except Exception as e:
        raise e

# Inicializa o contador de modificados
modificados = 0
# Converte o conjunto de índices None para uma lista e a embaralha
lista = list(indicesNones)
shuffle(lista)
for indice in lista:
    # Se a coluna 'dados' não for None, remove o índice do conjunto
    if df.iloc[indice]["dados"] is not None:
        indicesNones.remove(indice)
        continue

    # Obtém o ID do jogo
    id = df.iloc[indice]["gameID"]

    # Obtém as informações do jogo usando a função getInfo
    data = getInfo(id)

    # Se os dados não forem None, atualiza o DataFrame e incrementa o contador de modificados
    if data is not None:
        indicesNones.remove(indice)
        df.at[indice, "dados"] = data
        modificados += 1



print(f"Modificados: {modificados}")

Modificados: 0

In [ ]:
# Calcula a soma dos valores na coluna 'valor' para as linhas onde a coluna 'dados' não é None e onde é None
aux1 = sum([linha[2] for linha in df.values if linha[6] is not None])
aux2 = sum([linha[2] for linha in df.values if linha[6] is None])
print(f"Valores não nulos: {aux1}")
print(f"Valores nulos: {aux2}")
print(f"{(100 * aux2/(aux1+aux2)):.2f}%")

Valores não nulos: 8446899
Valores nulos: 253054
2.91%

In [ ]:
# Configura o pandas para exibir até 5000 linhas
pd.set_option('display.max_rows', 5000)
# Cria uma máscara para filtrar as linhas onde a coluna 'dados' é None
mask = [(linha[6] is None) for linha in df.values]
df

       num                                               nome  currentPlayers  \
0        1                                   Counter-Strike 2         1274295
1        2                                             Dota 2          697691
2        3                                PUBG: BATTLEGROUNDS          450881
3        4                                       Apex Legends          245878
4        5                               Source SDK Base 2007          168144
5        6                                 NARAKA: BLADEPOINT          155758
6        7                                 Grand Theft Auto V          127112
7        8                                               Rust          112892
8        9                                     Stardew Valley           99342
9       10                                   Wallpaper Engine           90378
10      11                                           V Rising           81462
11      12                                          Fallout 4           78208
12      13                                           Lost Ark           74607
13      14                                      Call of Duty®           74086
14      15                                        War Thunder           73062
15      16                                    Team Fortress 2           72461
16      17                                          Destiny 2           70416
17      18                     Tom Clancy's Rainbow Six Siege           68272
18      19                                   EA SPORTS FC™ 24           66294
19      20                                      HELLDIVERS™ 2           64454
20      21                              Football Manager 2024           63848
21      22                                           Unturned           59295
22      23                   Ghost of Tsushima DIRECTOR'S CUT           59159
23      24                                    Baldur's Gate 3           57018
24      25                                           Warframe           55778
25      26                                   Dead by Daylight           55291
26      27                                           Hades II           53188
27      28                                          Crab Game           53066
28      29                                  Hearts of Iron IV           52489
29      30                              Monster Hunter: World           51807
30      31                                         ELDEN RING           50559
31      32                        Sid Meier's Civilization VI           49835
32      33                                            Valheim           46158
33      34                                      7 Days to Die           46075
34      35                                       Overwatch® 2           40080
35      36                                Governor of Poker 3           40074
36      37                                           Spacewar           39561
37      38                                               DayZ           39495
38      39                           Total War: WARHAMMER III           39314
39      40                              Don't Starve Together           37127
40      41                             Euro Truck Simulator 2           36684
41      42                                         tModLoader           33862
42      43                                        The Sims™ 4           31672
43      44                                           PAYDAY 2           31250
44      45                                        Dying Light           30791
45      46                               Farming Simulator 22           30393
46      47                                         Fallout 76           30325
47      48                                              Hades           30091
48      49                                           RimWorld           29630
49      50                              ARK: Survival Evolved           28301
50      51                              Red Dead Redemption 2           26714
51      52                                        Garry's Mod           26651
52      53                                           Terraria           26645
53      54                                             VRChat           26092
54      55                                          Stellaris           25945
55      56                                        Hero's Land           25686
56      57                                     Cyberpunk 2077           25571
57      58                                           Palworld           24293
58      59                              Yu-Gi-Oh! Master Duel           23982
59      60                                  Street Fighter™ 6           23918
60      61                           FINAL FANTASY XIV Online           23306
61      62                                      Left 4 Dead 2           22572
62      63                                         Diablo® IV           22014
63      64                                               SCUM           21697
64      65                              Europa Universalis IV           21017
65      66                                    Project Zomboid           20896
66      67                                               MIR4           19995
67      68              Age of Empires II: Definitive Edition           19803
68      69                                      Albion Online           19764
69      70                                      Rocket League           19561
70      71                       Mount & Blade II: Bannerlord           19381
71      72                                        Manor Lords           19380
72      73                                        Crosshair X           19236
73      74                                       Black Desert           19131
74      75                                 Crusader Kings III           18853
75      76                                      Path of Exile           18709
76      77        The Elder Scrolls V: Skyrim Special Edition           18301
77      78                      The Binding of Isaac: Rebirth           18261
78      79                                       BeamNG.drive           17841
79      80                                      Summoners War           17766
80      81                                              Squad           17113
81      82                                     Slay the Spire           17098
82      83                                     Lethal Company           17081
83      84                                    Forza Horizon 5           17057
84      85                                  Russian Fishing 4           16931
85      86                         Sid Meier's Civilization V           16530
86      87                                      Geometry Dash           16405
87      88                                     Sea of Thieves           16386
88      89                                     Hunt: Showdown           15963
89      90                                 Fallout: New Vegas           15779
90      91                                               Raft           15720
91      92                           The Elder Scrolls Online           14973
92      93                             ARK: Survival Ascended           14964
93      94                                           Soundpad           14842
94      95                                           NBA 2K24           14735
95      96                                  Gray Zone Warfare           14662
96      97                                         THE FINALS           14597
97      98                           The Witcher 3: Wild Hunt           14362
98      99                                    Myth of Empires           14336
99     100                                            Balatro           14113
100    101                                  Battlefield™ 2042           14023
101    102                                     Battlefield™ V           13939
102    103                                      Assetto Corsa           13873
103    104                                MONSTER HUNTER RISE           13833
104    105             Age of Empires IV: Anniversary Edition           13556
105    106                                  World of Warships           13443
106    107                                   Cities: Skylines           13291
107    108                                  雀魂麻将(MahjongSoul)           13246
108    109                                         OBS Studio           13087
109    110                                           Factorio           12968
110    111                                         Brawlhalla           12734
111    112                                   Goose Goose Duck           12608
112    113                                    eFootball™ 2024           12533
113    114                                    Persona 5 Royal           12397
114    115                               World of Tanks Blitz           12393
115    116                                     Counter-Strike           12368
116    117                                       Phasmophobia           12136
117    118                                     Limbus Company           12037
118    119                              Football Manager 2023           11909
119    120                                     Eternal Return           11521
120    121                                        Bloons TD 6           11508
121    122                              Supermarket Simulator           11368
122    123                                             Arma 3           10942
123    124                             Counter-Strike: Source           10834
124    125                                    Content Warning           10669
125    126                                 Deep Rock Galactic           10624
126    127                                           TEKKEN 8           10585
127    128                                     Cookie Clicker           10547
128    129                                       VTube Studio           10405
129    130                                Oxygen Not Included           10305
130    131                                    DARK SOULS™ III            9633
131    132                           American Truck Simulator            9295
132    133                                     Risk of Rain 2            8999
133    134                                         Victoria 3            8982
134    135                                     Abiotic Factor            8945
135    136                                    Battlefield 1 ™            8824
136    137                                            Blender            8796
137    138                                       Satisfactory            8762
138    139                              Legends of Idleon MMO            8579
139    140                                    Killing Floor 2            8525
140    141                                               VPet            8524
141    142                                          STALCRAFT            8498
142    143                         Sekiro™: Shadows Die Twice            8392
143    144                                            Aimlabs            7781
144    145                                           NBA 2K23            7682
145    146                                              SMITE            7677
146    147                                              Palia            7447
147    148                                 Sons Of The Forest            7394
148    149                                          Starfield            7312
149    150                          Kingdom Come: Deliverance            7295
150    151                                       Conan Exiles            7277
151    152                          Total War: THREE KINGDOMS            7209
152    153                                                DSX            6989
153    154                         Microsoft Flight Simulator            6976
154    155                                  Vampire Survivors            6917
155    156                             SCP: Secret Laboratory            6730
156    157                                          YoloMouse            6724
157    158                                          New World            6610
158    159                                 EA SPORTS™ FIFA 23            6569
159    160                                    Forza Horizon 4            6541
160    161                                         Bellwright            6538
161    162                                  People Playground            6535
162    163                                 Rusty's Retirement            6497
163    164                                 The Planet Crafter            6399
164    165                           Divinity: Original Sin 2            6395
165    166                           Assassin's Creed Odyssey            6128
166    167                                       Stumble Guys            6108
167    168                                    Hogwarts Legacy            6044
168    169           Horizon Forbidden West™ Complete Edition            6012
169    170                                   Darkest Dungeon®            5922
170    171                                       It Takes Two            5852
171    172                                Cities: Skylines II            5750
172    173                                      Hollow Knight            5724
173    174                                         Enshrouded            5619
174    175                                           Grounded            5594
175    176         Cell to Singularity - Evolution Never Ends            5382
176    177                                         MapleStory            5321
177    178                                        Shop Titans            5291
178    179                                Company of Heroes 2            5203
179    180                                    Space Engineers            5197
180    181             Age of Empires III: Definitive Edition            5120
181    182                                   Backpack Battles            5116
182    183                                   Dragon's Dogma 2            5106
183    184                                           Paladins            5029
184    185               Total War: ROME II - Emperor Edition            5000
185    186                         Magic: The Gathering Arena            4971
186    187                                     Hell Let Loose            4962
187    188                                           The Isle            4950
188    189                                        Melvor Idle            4887
189    190                                       No Man's Sky            4886
190    191                                            Brotato            4867
191    192                                           Crossout            4805
192    193                    Dying Light 2: Reloaded Edition            4794
193    194                            DARK SOULS™: REMASTERED            4766
194    195                             Mount & Blade: Warband            4680
195    196                                             小黑盒加速器            4679
196    197                                     World of Tanks            4652
197    198                           Pixel Gun 3D: PC Edition            4639
198    199                      STAR WARS™: The Old Republic™            4625
199    200                                        MARVEL SNAP            4611
200    201                                    Fallout Shelter            4553
201    202                                    Resident Evil 4            4532
202    203                                       Ready or Not            4450
203    204                                Company of Heroes 3            4426
204    205                                         Last Epoch            4419
205    206                         Sky: Children of the Light            4343
206    207                                 Tabletop Simulator            4328
207    208                                         The Forest            4294
208    209                                           Aseprite            4256
209    210                         Assetto Corsa Competizione            4254
210    211                     Mass Effect™ Legendary Edition            4251
211    212                              Football Manager 2022            4204
212    213                                      Overcooked! 2            4197
213    214                                 Unnamed Space Idle            4172
214    215                        Call of Duty: Black Ops III            4161
215    216                                         Dead Cells            4120
216    217                           Granblue Fantasy: Relink            4108
217    218                         Warhammer 40,000: Darktide            4105
218    219                                         Planet Zoo            4101
219    220                                               鸡械绿洲            4092
220    221                                             Kenshi            4086
221    222               Plants vs. Zombies: Game of the Year            4068
222    223                       Deep Rock Galactic: Survivor            4056
223    224                                   Rabbit and Steel            4030
224    225                              鬼谷八荒 Tale of Immortal            3958
225    226                               Dyson Sphere Program            3939
226    227                                   Persona 3 Reload            3911
227    228                                         EVE Online            3906
228    229             Idle Champions of the Forgotten Realms            3875
229    230                                  100% Orange Juice            3874
230    231                                            FIFA 22            3800
231    232                                           NGU IDLE            3764
232    233                                           Among Us            3759
233    234                                     Fishing Planet            3734
234    235                                       Lust Goddess            3718
235    236                                      Party Animals            3710
236    237                                          For Honor            3689
237    238                                Total War: SHOGUN 2            3678
238    239                                         Remnant II            3615
239    240                           Disney Dreamlight Valley            3613
240    241                               Yu-Gi-Oh! Duel Links            3604
241    242        Total War: MEDIEVAL II - Definitive Edition            3581
242    243                                        ANIMAL WELL            3571
243    244                                      Feed The Cups            3541
244    245                                  Transport Fever 2            3527
245    246                                     DAVE THE DIVER            3509
246    247                           Age of Empires II (2013)            3489
247    248                                         Chrono Ark            3443
248    249                                             F1® 23            3440
249    250                                         Subnautica            3397
250    251                                             XCOM 2            3361
251    252                                    ENDLESS™ Legend            3355
252    253                       theHunter: Call of the Wild™            3284
253    254                               Escape the Backrooms            3271
254    255             Call to Arms - Gates of Hell: Ostfront            3249

In [ ]:
df.to_pickle("./jogosInfo.pkl")