In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import pandas as pd
from datetime import datetime, timedelta

In [ ]:
# Configuração das opções do navegador
options = Options()
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36")

# Inicializa o navegador com as opções configuradas
navegador = webdriver.Chrome(options=options)

# URL da página a ser acessada
url = "https://steamdb.info/charts/?all"
navegador.get(url)

In [ ]:
# Localiza a tabela de dados na página
tabela = navegador.find_element(By.CLASS_NAME, "dataTable")

# Localiza todos os elementos que representam apps na tabela
listaApps = tabela.find_elements(By.CLASS_NAME, "app")

# Lista para armazenar os dados extraídos
lista = []

# Lista para armazenar os tempos de execução de cada iteração
listaTempos = []
qtdFaltando = len(listaApps)

# Itera sobre cada app na lista de apps
for app in listaApps:

    start = datetime.now()

    # num = int(app.find_element(By.CLASS_NAME, "dt-type-numeric").text.replace(".", ""))

    # Extrai os elementos de tipo numérico
    aux = app.find_elements(By.CLASS_NAME, "dt-type-numeric")


    # Extrai o nome do app
    aux2 = app.find_elements(By.CSS_SELECTOR, "td")
    nome = aux2[2].text

    # Extrai e converte os dados de jogadores atuais, pico de 24h e pico de todos os tempos
    num = int(aux[0].text.replace(".", ""))
    currentPlayers = int(aux[2].text.replace(",", ""))
    peak24h = int(aux[3].text.replace(",", ""))
    allTimePeak = int(aux[4].text.replace(",", ""))

    # Extrai o ID do jogo a partir da URL
    gameID = aux2[2].find_element(By.TAG_NAME, "a").get_attribute("href")
    gameID = gameID.replace("https://steamdb.info/app/", "").replace("/charts/", "")
    gameID = int(gameID)

    # Adiciona os dados extraídos à lista
    lista.append([num, nome, currentPlayers, peak24h, allTimePeak, gameID])

    end = datetime.now()


    # print(num, nome, currentPlayers, peak24h, allTimePeak)

    qtdFaltando-=1
    listaTempos.append((end - start).total_seconds())

    # A cada 100 iterações, calcula o tempo médio e estima o horário de término
    if(num%100 == 0):
        mediaSegundos = sum(listaTempos) / len(listaTempos)
        hora = datetime.now() + timedelta(seconds=mediaSegundos*qtdFaltando)
        stringHora = hora.strftime("%H:%M:%S")
        print(f"{num}: Horário esperado de término: {stringHora}")

    # break

# Converte a lista de dados para um DataFrame do pandas
df = pd.DataFrame(lista, columns=["num", "nome", "currentPlayers", "peak24h", "allTimePeak", "gameID"])
df

100: Horário esperado de término: 12:22:47
200: Horário esperado de término: 12:22:33
300: Horário esperado de término: 12:22:56
400: Horário esperado de término: 12:22:50
500: Horário esperado de término: 12:22:37
600: Horário esperado de término: 12:22:26
700: Horário esperado de término: 12:22:45
800: Horário esperado de término: 12:22:51
900: Horário esperado de término: 12:22:54
1000: Horário esperado de término: 12:22:52
1100: Horário esperado de término: 12:22:51
1200: Horário esperado de término: 12:22:49
1300: Horário esperado de término: 12:22:51
1400: Horário esperado de término: 12:22:51
1500: Horário esperado de término: 12:22:47
1600: Horário esperado de término: 12:22:43
1700: Horário esperado de término: 12:22:38
1800: Horário esperado de término: 12:22:40
1900: Horário esperado de término: 12:22:35
2000: Horário esperado de término: 12:22:29
2100: Horário esperado de término: 12:22:24
2200: Horário esperado de término: 12:22:25
2300: Horário esperado de término: 12:22:24
2400: Horário esperado de término: 12:22:23
2500: Horário esperado de término: 12:22:20
2600: Horário esperado de término: 12:22:23
2700: Horário esperado de término: 12:22:24
2800: Horário esperado de término: 12:22:17
2900: Horário esperado de término: 12:22:10
3000: Horário esperado de término: 12:22:48
3100: Horário esperado de término: 12:22:47
3200: Horário esperado de término: 12:22:48
3300: Horário esperado de término: 12:22:48
3400: Horário esperado de término: 12:22:58
3500: Horário esperado de término: 12:22:55
3600: Horário esperado de término: 12:22:52
3700: Horário esperado de término: 12:22:49
3800: Horário esperado de término: 12:22:46
3900: Horário esperado de término: 12:22:42
4000: Horário esperado de término: 12:22:40
4100: Horário esperado de término: 12:22:38
4200: Horário esperado de término: 12:22:35
4300: Horário esperado de término: 12:22:29
4400: Horário esperado de término: 12:22:37
4500: Horário esperado de término: 12:22:32
4600: Horário esperado de término: 12:22:31
4700: Horário esperado de término: 12:22:37
4800: Horário esperado de término: 12:22:36
4900: Horário esperado de término: 12:22:34
5000: Horário esperado de término: 12:22:31

,num,nome,currentPlayers,peak24h,allTimePeak,gameID
0,1,Counter-Strike 2,1274295,1527573,1818773,730
1,2,Dota 2,697691,716906,1295114,570
2,3,PUBG: BATTLEGROUNDS,450881,631467,3257248,578080
3,4,Apex Legends,245878,357225,624473,1172470
4,5,Source SDK Base 2007,168144,187294,221857,218
...,...,...,...,...,...,...
4995,4996,Devil Slayer - Raksasi / 斩妖Raksasi,20,26,1080,1016600
4996,4997,DEEEER Simulator: Your Average Everyday Deer Game,20,25,251,1018800
4997,4998,Wanba Warriors,20,31,720,1021770
4998,4999,Coloring Game,20,31,593,1026820
4999,5000,Blood Trail,20,40,154,1032430

In [ ]:
len(lista)

2291

In [ ]:
df.to_pickle("listaPlayersNomeJogo.pkl")

In [ ]:
pd.read_pickle("listaPlayersNomeJogo.pkl")

,num,nome,currentPlayers,peak24h,allTimePeak,gameID
0,1,Counter-Strike 2,1274295,1527573,1818773,730
1,2,Dota 2,697691,716906,1295114,570
2,3,PUBG: BATTLEGROUNDS,450881,631467,3257248,578080
3,4,Apex Legends,245878,357225,624473,1172470
4,5,Source SDK Base 2007,168144,187294,221857,218
...,...,...,...,...,...,...
4995,4996,Devil Slayer - Raksasi / 斩妖Raksasi,20,26,1080,1016600
4996,4997,DEEEER Simulator: Your Average Everyday Deer Game,20,25,251,1018800
4997,4998,Wanba Warriors,20,31,720,1021770
4998,4999,Coloring Game,20,31,593,1026820
4999,5000,Blood Trail,20,40,154,1032430